ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'USER_REGISTERED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LESSON_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'COURSE_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PROJECT_SUBMITTED';
